---
kind: template
load: container_v1.yaml
name: build-and-push
data:
  build:
    containerRepo: livspace/gubernator
    disableCache: true
  promote:
    deploymentRepo: core-infra-deployments
    appName: gubernator
